/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ctr_constants.h"

namespace DmtecCtr {

const ctrConstants g_ctr_constants;

ctrConstants::ctrConstants() {
}

} // namespace

