/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ctr_CONSTANTS_H
#define ctr_CONSTANTS_H

#include "ctr_types.h"

namespace DmtecCtr {

class ctrConstants {
 public:
  ctrConstants();

};

extern const ctrConstants g_ctr_constants;

} // namespace

#endif
